feat(deploy-pack): add blank `lephare_packagist_com_token` to Ansible vault
le-phare/flex-recipes pull request #27
Opened 2023-08-25 13:00 UTC by lucasmirloup

When the `lephare_packagist_com_token` Ansible variable isn't set (in the Vault or elsewhere), [the `private_registry` Ansible job that installs a Packagist.com token is skipped](https://github.com/le-phare/ansible-deploy/blob/9b8e6d87e1ac9e21e9541b8a8280a2ab5da6c5a6/config/steps/composer/private_registry.yml#L13), triggering Composer's `AUTHENTICATION FAILURE` errors.

Setting this variable in the vault encourages the developer to configure it and avoid Composer errors.

2023-08-25 13:33 UTC, pierreboissinot requested changes

2023-08-25 13:33 UTC, pierreboissinot commented on faros-ng/deploy-pack/1.5/ansible/preprod/group_vars/app/vault
> +lephare_packagist_com_token: <lephare_packagist_com_token>
Toute variable dans le vault devrait avoir le prefix `vault_`, afin de ne pas se compliquer avec des changements sur lephare/ansible-deploy,  pour résoudre ton problème, il vaut mieux que la recipe définisse la variable dans le `_variables.yml` au niveau du playbook:
```
lephare_packagist_com_token: "{{ vault_packagist_com_token }}"
```

2023-09-12 12:51 UTC, thislg approved these changes

2023-09-12 14:51 UTC, pierreboissinot approved these changes

2023-09-12 14:56 UTC, merged